services:
  BE_191711_prestashop:
    container_name: prestashop
    image: prestashop/prestashop:1.7.8
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "19171:443"
    environment:
      DB_SERVER: db
      DB_NAME: BE_191711
      DB_USER: student
      DB_PASSWD: root
      PS_INSTALL_AUTO: 1
      PS_DEV_MODE: 1
    # volumes:
    #   - ./src:/var/www/html
    #   - ./data/cert.pem:/etc/ssl/certs/cert.pem
    #   - ./data/key.pem:/etc/ssl/private/key.pem
    #   - ./data/presta.conf:/etc/apache2/sites-available/presta.conf
    build:
      context: .
      dockerfile: Dockerfile

  BE_191711_memcached:
    container_name: presta_cache
    image: memcached:alpine3.21

  db:
    container_name: db
    image: mariadb:10.3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: student
      MYSQL_DATABASE: BE_191711
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/